const express=require('express'),fs=require('fs'),path=require('path'),jwt=require('jsonwebtoken'),multer=require('multer');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'change_me_before_production';
const DATA=path.join(__dirname,'data');fs.mkdirSync(DATA,{recursive:true});const file=n=>path.join(DATA,n+'.json');
const read=n=>{try{return JSON.parse(fs.readFileSync(file(n),'utf8'))}catch{return[]}};const write=(n,d)=>fs.writeFileSync(file(n),JSON.stringify(d,null,2));
const auth=(req,res,next)=>{try{jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);next()}catch{res.status(401).json({message:'Admin login required'})}};
app.use(express.json({limit:'5mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));
const storage=multer.diskStorage({destination:(q,r,cb)=>{const d=path.join(__dirname,'public','uploads');fs.mkdirSync(d,{recursive:true});cb(null,d)},filename:(q,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))});const upload=multer({storage});
app.post('/api/login',(req,res)=>req.body.email==='admin@college.com'&&req.body.password==='admin123'?res.json({token:jwt.sign({admin:1},SECRET,{expiresIn:'8h'})}):res.status(401).json({message:'Invalid credentials'}));
const collections=['resources','announcements','projects','calendar','companies','jobs','internships','company_preparation','placement_questions','placement_experiences','courses','skills','interview_questions','aptitude_questions','results','useful_links','roadmaps','daily_practice','job_applications'];
for(const n of collections){app.get('/api/'+n,(req,res)=>res.json(read(n)));app.post('/api/'+n,auth,(req,res)=>{let d=read(n);let item={id:Date.now()+Math.floor(Math.random()*1000),createdAt:new Date().toISOString(),...req.body};d.push(item);write(n,d);res.json(item)});app.put('/api/'+n+'/:id',auth,(req,res)=>{let d=read(n),i=d.findIndex(x=>String(x.id)===String(req.params.id));if(i<0)return res.status(404).json({message:'Not found'});d[i]={...d[i],...req.body,updatedAt:new Date().toISOString()};write(n,d);res.json(d[i])});app.delete('/api/'+n+'/:id',auth,(req,res)=>{write(n,read(n).filter(x=>String(x.id)!==String(req.params.id)));res.json({ok:true})})}
app.post('/api/resources/upload',auth,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({message:'Please select a file'});let d=read('resources'),x={id:Date.now(),type:req.body.type||'PDF',title:req.body.title||req.file.originalname,description:req.body.description||'',url:'uploads/'+req.file.filename,fileName:req.file.originalname};d.push(x);write('resources',d);res.json(x)});
app.get('/api/admin/summary',auth,(req,res)=>{let o={};for(const n of collections)o[n]=read(n).length;res.json(o)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('Engineering Student Portal running on '+PORT));
