const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const PORT=process.env.PORT||3000, ROOT=__dirname, DATA=path.join(ROOT,'data'), PUBLIC=path.join(ROOT,'public'), SECRET=process.env.JWT_SECRET||'engineering-student-portal-local-secret';
fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(path.join(PUBLIC,'uploads'),{recursive:true});
const file=n=>path.join(DATA,n+'.json');
const read=n=>{try{const d=JSON.parse(fs.readFileSync(file(n),'utf8'));return Array.isArray(d)?d:[];}catch{return[];}};
const write=(n,d)=>fs.writeFileSync(file(n),JSON.stringify(d,null,2));
const token=()=>{const p=Buffer.from(JSON.stringify({admin:1,exp:Date.now()+8*3600e3})).toString('base64url');const s=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');return p+'.'+s};
const auth=req=>{const h=req.headers.authorization||'',t=h.replace(/^Bearer\s+/,'').split('.');if(t.length!==2)return false;const s=crypto.createHmac('sha256',SECRET).update(t[0]).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(t[1])))return false;try{return JSON.parse(Buffer.from(t[0],'base64url')).exp>Date.now()}catch{return false}};
const collections=['resources','announcements','projects','calendar','companies','jobs','internships','company_preparation','placement_questions','placement_experiences','courses','skills','interview_questions','aptitude_questions','results','useful_links','roadmaps','daily_practice','job_applications','coding_questions'];
function send(res,status,obj,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type==='application/json'?JSON.stringify(obj):obj)}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>3e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{resolve({})}});req.on('error',reject)})}
const server=http.createServer(async(req,res)=>{const u=url.parse(req.url,true),p=u.pathname;
 if(p==='/api/health')return send(res,200,{ok:true,service:'Engineering Student Portal'});
 if(p==='/api/login'&&req.method==='POST'){const b=await body(req);return b.email==='admin@college.com'&&b.password==='admin123'?send(res,200,{token:token()}):send(res,401,{message:'Invalid credentials'})}
 if(p.startsWith('/api/')){const m=p.match(/^\/api\/([^/]+)(?:\/(\d+))?$/);if(!m)return send(res,404,{message:'API not found'});const n=m[1],id=m[2];if(!collections.includes(n))return send(res,404,{message:'Collection not found'});if(req.method==='GET')return send(res,200,read(n));if(!auth(req))return send(res,401,{message:'Admin login required'});if(req.method==='POST'){const b=await body(req),d=read(n),item={id:Date.now()+Math.floor(Math.random()*1000),createdAt:new Date().toISOString(),...b};d.push(item);write(n,d);return send(res,200,item)}if(req.method==='PUT'&&id){const d=read(n),i=d.findIndex(x=>String(x.id)===id);if(i<0)return send(res,404,{message:'Item not found'});const b=await body(req);d[i]={...d[i],...b,id:d[i].id,updatedAt:new Date().toISOString()};write(n,d);return send(res,200,d[i])}if(req.method==='DELETE'&&id){write(n,read(n).filter(x=>String(x.id)!==id));return send(res,200,{ok:true})}return send(res,405,{message:'Method not allowed'})}
 let fp=path.join(PUBLIC,p==='/'?'index.html':p.replace(/^\//,''));if(!fp.startsWith(PUBLIC)||!fs.existsSync(fp)||fs.statSync(fp).isDirectory())fp=path.join(PUBLIC,'index.html');const ext=path.extname(fp).toLowerCase(),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(fp).pipe(res);
});server.listen(PORT,'0.0.0.0',()=>console.log('Engineering Student Portal running on '+PORT));
